% Matlab function to calculate the updated estimate of inertia tensor
% It takes the values of error, p revious estimate and sample time 
 
function [Phat, Jtilde] = calculate_Jtilde(eA, omega, alpha_D, Phat, dt,J_gain)
    Y1 = [0 omega(2)*omega(3) -omega(2)*omega(3) omega(1)*omega(3) -omega(1)*omega(2) omega(3)^2-omega(2)^2;...
          -omega(1)*omega(3) 0 omega(1)*omega(3) -omega(2)*omega(3) omega(1)^2-omega(3)^2 omega(1)*omega(2);...
          omega(1)*omega(2) -omega(1)*omega(2) 0 omega(2)^2-omega(1)^2 omega(3)*omega(2) -omega(3)*omega(2)];
    Y3 = [alpha_D(1) 0 0 alpha_D(2) alpha_D(3) 0; ...
          0 alpha_D(2) 0 alpha_D(1) 0 alpha_D(3);...
          0 0 alpha_D(3) 0 alpha_D(1) alpha_D(2)];
    Y = -Y3 + Y1;
    YteA = Y'*eA;
    B = [YteA(2)+YteA(3) -0.5*YteA(4) -0.5*YteA(5);... 
             -0.5*YteA(4) YteA(1)+YteA(3)  -0.5*YteA(6);...
              -0.5*YteA(5)  -0.5*YteA(6) YteA(1)+YteA(2)];
    Phatdot = 1/J_gain*Phat*B*Phat; 
    Phat = Phat + Phatdot*dt;
    Jtilde = [Phat(2,2)+Phat(3,3) -Phat(1,2) -Phat(1,3);...
              -Phat(1,2) Phat(1,1)+Phat(3,3) -Phat(2,3);...
               -Phat(1,3) -Phat(2,3) Phat(1,1)+Phat(2,2)];